### PR TITLE
Allow batch debts to be added in pounds.

### PR DESCRIPTION
**Pull request by d-nagy**
Just a quality of life change - before it was pence, and members of the exec thought it was odd.

### CODE REVIEW

**Comment by d-nagy** [comment]
Same build failure as for pull request #56 - I'm still not sure what is causing it, other than this link in ```src/models/user.js``` not giving a valid response.:
```
var options = {
     url: 'https://community.dur.ac.uk/grey.jcr/itsuserdetailsjson.php?username=' + username
 };
```
 I'm not sure how, if at all, I've managed to mess that up.

**Comment by ben-willis** [comment]
So the reason I used pence was I was worried about types (Int vs Float). If you've tested this then I'm happy to merge.

As an aside this is exactly the kind of thing we need to write tests for.

**Comment by d-nagy** [comment]
Ok, that makes sense. I'll do some more testing and try and write a test, and then update you. Should I just close this this pull request now?

**Comment by ben-willis** [comment]
If you've tested it manually I'm happy to take your word for it!

**Comment by d-nagy** [comment]
To be perfectly honest, I have not tested this enough - I'd like to make sure I can't break it first.

**Pull request closed without merging**
