### PR TITLE
Update menu.pug

### PR DESCRIPTION
**Pull request by Kiran-Crawford**
I don't know if this actually works or anything

### CODE REVIEW

**Review by ben-willis — COMMENTED** [review]
Looks good, because "crowdfunding" isn't actually a page on the website you can just set: class='item'

Also there's something weird going on with that href tag being repeated.

Once you've fixed these I'll go ahead and merge, thanks for contributing!

**Comment by Kiran-Crawford** [comment]
Thanks, I've fixed those now

**Comment by Kiran-Crawford** [comment]
Managed to get the postresql stuff working enough on my computer so it would run the website and corrected the code so the latest update actually works

**Comment by Kiran-Crawford** [comment]
Ben Firth asked for it to be yellow to highlight it as it's new, so I just put it in as inline style

**Comment by ben-willis** [comment]
Glad you could get this working. If you want to change the style of anything the website uses Semantic UI for that. Documentation on menus is available here:
https://semantic-ui.com/collections/menu.html
You'll just need to change the class from 'item' to something like 'yellow item'.

If that doesn't work and you don't find anything else useful the inline style is fine and I'll merge the request.

Also if you have any questions about getting the website running for testing I'm happy to help!

**Comment by Kiran-Crawford** [comment]
It seems that Semantic doesn't have an option for changing the inactive colour of an item, adding a colour on an item will only change it when active and you can only change the colour for when it's not selected as a whole menu, not individual items. It looks like inline styles will probably have to do for now.
Thanks for the link to the docs though- its much easier than looking through the css files which is what I was trying to do earlier

**Comment by Kiran-Crawford** [comment]
The problem I'm having with getting it for testing is when i run npm run seed-postgres I get an error of either  "insert or update on table "folders" violates foreign key constraint "folders_owner_foreign"" or " insert or update on table "user_roles" violates foreign key constraint "user_roles_role_id_foreign"".
I'm guessing I probably haven't set up the database right as I didn't really have a clue what I was doing with that stuff.

**Comment by ben-willis** [comment]
In that case I'll merge the pull request as is.

That error is a little confusing. You only need to run it once when initially setting up the project so there is a chance that it did actually work the first time. What happens when you run npm run start?

**Comment by Kiran-Crawford** [comment]
The website does run on localhost:3000, but the terminal spews out a load of 'cannot read property 'level' of undefined'  errors in the terminal, and logging into the website doesn't work

**Comment by Kiran-Crawford** [comment]
Also once an edit is merged what happens now? I'm guessing Micheal has to do something with the server?

**Comment by ben-willis** [comment]
Ah the "cannot read level of undefined" is a known issue but shouldn't cause the problem with logging in. Can you work out if there's another error when you log in?

Yeah Micheal needs to pull the changes and restart the site.

**Comment by Kiran-Crawford** [comment]
Logging in is being very weird and doing different things each time I do it,  Originally when I tried to log in it would just send me back to the homepage without me being logged in, but randomly after doing it loads of times it somehow worked and I'm now permanently logged in on google chrome and can't log out even when I restart the website. 
Was the seed postgres thing meant to add an admin section to the website when I'm logged in - I can't see it anywhere and going to /admin gives 403 forbidden 
I tried in a chrome incognito window, and there I try to log in, no matter what page I was on before it sends me to http://localhost:3000/services/debt with an Unauthorized. Redirecting to /login?unauthorised 
I then tried in internet explorer and that is doing what it originally was in chrome just taking me to the homepage not logged in

**Comment by Kiran-Crawford** [comment]
There's quite a few errors that come up, I've attached some text files with everything that happens after I log in, I think that the login1.txt might have been the time where it actually worked, login2.txt definitely didn't work
[login1.txt](https://github.com/ben-willis/grey-jcr/files/1644044/login1.txt)
[login2.txt](https://github.com/ben-willis/grey-jcr/files/1644045/login2.txt)

**Comment by ben-willis** [comment]
Hmmm looks like an issue with the persmissions on the folder. I have to admit I haven't properly tested the website on Windows.

You can try right clicking on the grey-jcr folder then properties then security and try to give your user any permissions it's missing. Alternatively you could run the command prompt as administrator and run npm run start from there.

If I get time I'll make some changes to how the website runs to avoid this but I'll let you know.

**Pull request merged**
