### PR TITLE
Remove phoenix ball promo

### PR DESCRIPTION
**Pull request by Kiran-Crawford**
Phoenix ball was a long time ago so the promo should really go
I haven't been able to get docker to work again on my laptop and so haven't been able to test this, can someone check that this code definitely still works before merging?

### CODE REVIEW

**Comment by ben-willis** [comment]
What are your thoughts on stopping using Docker? Seems to have caused more problems than it's solved (can't be run easily on Windows, performance issues). @d-nagy any thoughts?

**Comment by d-nagy** [comment]
I'm not gonna lie, I found it great to be honest (maybe I've gotten lucky).
So far I've been running it on Debian and its worked fine. I found it makes
installation easier just because it handles postgresql. I've not tried it
on Windows though before, so I can't comment on that side of it. I also
haven't really noticed performance issues, but that also could easily be me
being oblivious to things.

I would be interested to know the kinds of issues we are having though with
it. I may try my hand at getting it working on Windows and see what happens.

**Comment by d-nagy** [comment]
Right - Windows is trickier. I encountered this apparent bug: 
https://github.com/docker-library/postgres/issues/435
https://github.com/docker/for-win/issues/445

This meant I had to modify docker-compose.yml 

Other than this however, I found it not too bad (again, maybe I got lucky).

I used Git for Windows: https://gitforwindows.org/

and installed Docker from here: https://store.docker.com/editions/community/docker-ce-desktop-windows

and then followed the website installation instructions and things seemed to work.

My new docker-compose.yml:
[docker-compose.zip](https://github.com/ben-willis/grey-jcr/files/2430616/docker-compose.zip)

**Comment by ben-willis** [comment]
Ah that's good. Let's get a PR in for that new docker-compose file.

**Pull request merged**
