### PR TITLE
Prevent PayPal payment debts being duplicated

### PR DESCRIPTION
**Pull request by d-nagy**
Fix to prevent the following situation, shown to me by FACSO:

image

Not sure what the cause of the problem was, it was supposedly not a one-off. The fix checks whether a debt with the same payment ID has already been added and only adds the debt if not.

The fix passes the tests, but I haven't been able to reproduce the problem to check whether it works.

### CODE REVIEW

**Comment by ben-willis** [comment]
LGTM. Can you maybe put some kind of logging if there is duplicate? Could help us work out how often it's happening.

**Comment by d-nagy** [comment]
Yeah no problem - with regards to logging though, I see that we have morgan but don't use it anywhere (unless I am mistaken) - should I use that?

**Comment by ben-willis** [comment]
Morgan is used for logging HTTP requests. You can just use console.log for now.

**Comment by d-nagy** [comment]
Goddammit sorry I didn't mean to add package-lock.json

**Review by ben-willis — APPROVED** [review]

**Pull request merged**
